### ISSUE TITLE
Reproduce SSD MLCube run

### ISSUE THREAD

**Issue by bitfort** [mlcommons/mlcube#185]
Here is the PR in the training repo;
https://github.com/mlcommons/training/pull/465

Note: this may not finish due to not having a GPU to run on.

**Comment by davidjurado** [comment]
Hello Victor,

I was able to reproduce all the steps described in **current implementation** section, the only additional step I needed to run mlcube was to manually install a dependency, the **tornado** package, the command that worked for me was:

```python -m pip install tornado```

I tried to run it on Mac and Ubuntu: For mac, the only mlcube command that worked was ```mlcube describe```, the other commands tried to run Docker with the ``` --gpus=all``` parameter, and this laptop doesn't have a GPU. For Ubuntu, it was able to execute all the scripts, but when training it failed since the GPU there is small, in the end, I got: ```“RuntimeError: CUDA error: out of memory”```

These were the final outputs for [Mac](https://i.imgur.com/Z24IhCq.png) and [Ubuntu](https://i.imgur.com/Pj0sHHi.png).

**Comment by bitfort** [comment]
Great to hear your dev instance is set up! Feel free to follow up on #186 now that your dev env is working :)
